### ISSUE TITLE
Cannot run application in Azure Cloudshell Environment

### ISSUE THREAD

**Issue by KrausJa** [MicrosoftDocs/mslearn-control-access-to-azure-storage-with-sas#4]
I tried fo follow the azure tutorial on [Control Access to Azure Storage with SAS]( https://docs.microsoft.com/en-us/learn/modules/control-access-to-azure-storage-with-sas/4-exercise-use-shared-access-signatures?source=learn).

I was not able to the run the web application (see step 10).

The displayed error is:

````sh
A compatible installed .NET Core SDK for global.json version [2.2.401] from [/home/userXY/sas/global.json] was not found
Install the [2.2.401] .NET Core SDK or update [/home/userXY/sas/global.json] with an installed .NET Core SDK:
  3.1.403 [/usr/share/dotnet/sdk]
  ````
  
  I also tried to install the expected .net Core SDK Version. But I don't have rights to do that.

**Comment by AOphagen** [comment]
> I tried fo follow the azure tutorial on [Control Access to Azure Storage with SAS](https://docs.microsoft.com/en-us/learn/modules/control-access-to-azure-storage-with-sas/4-exercise-use-shared-access-signatures?source=learn).
> 
> I was not able to the run the web application (see step 10).
> 
> The displayed error is:
> 
> ```shell
> A compatible installed .NET Core SDK for global.json version [2.2.401] from [/home/userXY/sas/global.json] was not found
> Install the [2.2.401] .NET Core SDK or update [/home/userXY/sas/global.json] with an installed .NET Core SDK:
>   3.1.403 [/usr/share/dotnet/sdk]
> ```
> 
> I also tried to install the expected .net Core SDK Version. But I don't have rights to do that.

I tried to reconfigure the project to use `.Net Core SDK 3.1.403` in `~/sasglobal.json` and `~/sas/patient-records.csproj` instead (the other option for a solution in the error message). I was not successful. Maybe you are more skillful tweeking the `.csproj`-File?

**Comment by marting71** [comment]
I also have the issue after trying the same steps as AOphagen.
As a non-Dev I'm out of my depth trying to tweak the code; I'm just starting the AZ-104 Admin course!
Can someone that understands this please update the code?
Thanks!

**Comment by unstableunicorn** [comment]
I have created a PR: #5 that should solve this, they may come back with requested changes, however if you do hit this in the mean time use the following clone in step 3 until a fix is implemented and you should be able to complete this section of the course.
```
git clone https://github.com/unstableunicorn/mslearn-control-access-to-azure-storage-with-sas.git sas
```
Alternatively, make the changes shown in the PR locally in the cloud shell to get you going! Happy learning!

**Comment by Houssem-Azzouz** [comment]
> 
> 
> I have created a PR: #5 that should solve this, they may come back with requested changes, however if you do hit this in the mean time use the following clone in step 3 until a fix is implemented and you should be able to complete this section of the course.
> 
> ```
> git clone https://github.com/unstableunicorn/mslearn-control-access-to-azure-storage-with-sas.git sas
> ```
> 
> Alternatively, make the changes shown in the PR locally in the cloud shell to get you going! Happy learning!

Thank you! I have used the updated code and I was able to complete the exercise.

**Comment by patridge** [comment]
For some reason, the Azure auth system seemed to be fine with me today and the code in #5 worked. It's been merged and this issue _should_ be resolved. Thank you, everyone, for all the help getting it fixed.
